<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Resend" Version="0.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealTimeSupportChat.Application\RealTimeSupportChat.Application.csproj" />
    <ProjectReference Include="..\RealTimeSupportChat.Identity\RealTimeSupportChat.Identity.csproj" />
  </ItemGroup>

</Project>
